import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { randomUUID } from "node:crypto";
import { resolve } from "node:path";
import { TOOL_ROOT } from "./config.js";
import { zeroUsage } from "./claude.js";
import type { NotedStep, RunState, TaskSpec } from "./types.js";

export const RUNS_DIR = resolve(TOOL_ROOT, ".runs");

function ensureDir(): void {
  if (!existsSync(RUNS_DIR)) mkdirSync(RUNS_DIR, { recursive: true });
}

function nowIso(): string {
  return new Date().toISOString();
}

/** Short, sortable, filesystem-safe id. */
function shortId(): string {
  const stamp = nowIso().replace(/[-:T]/g, "").slice(0, 14);
  return `${stamp}-${randomUUID().slice(0, 6)}`;
}

export function newRun(task: TaskSpec): RunState {
  const ts = nowIso();
  return {
    id: shortId(),
    createdAt: ts,
    updatedAt: ts,
    task,
    currentStage: "analysis",
    status: "running",
    attempts: {},
    totalIterations: 0,
    history: [],
    context: [],
    totals: zeroUsage(),
  };
}

export function saveRun(state: RunState): void {
  ensureDir();
  state.updatedAt = nowIso();
  writeFileSync(resolve(RUNS_DIR, `${state.id}.json`), JSON.stringify(state, null, 2), "utf8");
}

export function loadRun(id: string): RunState {
  return JSON.parse(readFileSync(resolve(RUNS_DIR, `${id}.json`), "utf8")) as RunState;
}

export function listRuns(): RunState[] {
  ensureDir();
  return readdirSync(RUNS_DIR)
    .filter((f) => f.endsWith(".json"))
    .map((f) => JSON.parse(readFileSync(resolve(RUNS_DIR, f), "utf8")) as RunState)
    .sort((a, b) => b.createdAt.localeCompare(a.createdAt));
}

export function latestRun(): RunState | undefined {
  return listRuns()[0];
}

// --- Per-step task files -----------------------------------------------------

/** File name (numbered to match the pipeline) for each step's generated task note. */
const STEP_FILE: Record<NotedStep, string> = {
  interface: "1-interface.md",
  tdd: "2-tdd.md",
  implementation: "4-implementation.md",
};

/** Directory holding a run's per-step task files. */
export function runStepDir(id: string): string {
  return resolve(RUNS_DIR, id);
}

/**
 * Write each step's focused notes (from the analysis plan) to its own file, so the
 * step reads only its task and you can inspect/edit it before the step runs.
 */
export function writeStepTasks(state: RunState): void {
  const notes = state.plan?.stepNotes;
  if (!notes) return;
  const dir = runStepDir(state.id);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  for (const step of Object.keys(STEP_FILE) as NotedStep[]) {
    const lines = notes[step];
    if (!lines?.length) continue;
    const body = [`# Task notes — ${step} (generated by the analysis stage)`, "", ...lines.map((l) => `- ${l}`), ""].join("\n");
    writeFileSync(resolve(dir, STEP_FILE[step]), body, "utf8");
  }
}

/**
 * Load a step's task note. The on-disk file wins (so your manual edits take effect);
 * falls back to the notes stored in the plan.
 */
export function loadStepTask(state: RunState, step: NotedStep): string | undefined {
  const file = resolve(runStepDir(state.id), STEP_FILE[step]);
  if (existsSync(file)) {
    const txt = readFileSync(file, "utf8").trim();
    if (txt) return txt;
  }
  const lines = state.plan?.stepNotes?.[step];
  return lines?.length ? lines.map((l) => `- ${l}`).join("\n") : undefined;
}
