import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { randomUUID } from "node:crypto";
import { resolve } from "node:path";
import { TOOL_ROOT } from "./config.js";
import { zeroUsage } from "./claude.js";
import type { NotedStep, RunState, TaskSpec } from "./types.js";

export const RUNS_DIR = resolve(TOOL_ROOT, ".runs");

function ensureDir(): void {
  if (!existsSync(RUNS_DIR)) mkdirSync(RUNS_DIR, { recursive: true });
}

function nowIso(): string {
  return new Date().toISOString();
}

/** Short, sortable, filesystem-safe id. */
function shortId(): string {
  const stamp = nowIso().replace(/[-:T]/g, "").slice(0, 14);
  return `${stamp}-${randomUUID().slice(0, 6)}`;
}

export function newRun(task: TaskSpec): RunState {
  const ts = nowIso();
  return {
    id: shortId(),
    createdAt: ts,
    updatedAt: ts,
    task,
    currentStage: "analysis",
    status: "running",
    attempts: {},
    totalIterations: 0,
    history: [],
    context: [],
    totals: zeroUsage(),
  };
}

export function saveRun(state: RunState): void {
  ensureDir();
  state.updatedAt = nowIso();
  writeFileSync(resolve(RUNS_DIR, `${state.id}.json`), JSON.stringify(state, null, 2), "utf8");
}

export function loadRun(id: string): RunState {
  return JSON.parse(readFileSync(resolve(RUNS_DIR, `${id}.json`), "utf8")) as RunState;
}

export function listRuns(): RunState[] {
  ensureDir();
  return readdirSync(RUNS_DIR)
    .filter((f) => f.endsWith(".json"))
    .map((f) => JSON.parse(readFileSync(resolve(RUNS_DIR, f), "utf8")) as RunState)
    .sort((a, b) => b.createdAt.localeCompare(a.createdAt));
}

export function latestRun(): RunState | undefined {
  return listRuns()[0];
}

// --- Per-step task files -----------------------------------------------------

/** File name (numbered to match the pipeline) for each step's generated task note. */
const STEP_FILE: Record<NotedStep, string> = {
  interface: "1-interface.md",
  tdd: "2-tdd.md",
  implementation: "4-implementation.md",
};

/** Directory holding a run's per-step task files. */
export function runStepDir(id: string): string {
  return resolve(RUNS_DIR, id);
}

/**
 * Compose the full spec the analysis stage produced for one step, drawing on the
 * richest plan data for that step (interface signatures / the test list with
 * per-case intent / implementation notes) plus its focused `stepNotes`. Returns
 * `undefined` when the plan carries nothing for the step.
 */
function stepSpec(state: RunState, step: NotedStep): string | undefined {
  const plan = state.plan;
  if (!plan) return undefined;
  const notes = plan.stepNotes?.[step];
  const sections: string[] = [];

  if (step === "interface" && plan.interfaces.length) {
    sections.push("## Interfaces to create");
    for (const i of plan.interfaces) {
      sections.push(`### ${i.file} — ${i.purpose}`, ...i.methods.map((m) => `- ${m}`));
    }
  }
  if (step === "tdd" && plan.tests.length) {
    sections.push("## Tests to write (what each test must do)");
    for (const t of plan.tests) {
      sections.push(`### ${t.file}`, ...t.cases.map((c) => `- ${c}`));
    }
  }
  if (step === "implementation" && plan.implementationNotes.length) {
    sections.push("## Implementation notes", ...plan.implementationNotes.map((n) => `- ${n}`));
  }
  if (notes?.length) {
    sections.push("## Focused notes (files to touch / warnings)", ...notes.map((l) => `- ${l}`));
  }

  if (!sections.length) return undefined;
  return [`# ${step} spec (generated by the analysis stage)`, "", ...sections, ""].join("\n");
}

/**
 * Write each step's full spec (from the analysis plan) to its own file, so the
 * step reads only its own task and you can inspect/edit it before the step runs.
 * The analysis stage produces one file per step: interfaces, tests, implementation.
 */
export function writeStepTasks(state: RunState): void {
  if (!state.plan) return;
  const dir = runStepDir(state.id);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  for (const step of Object.keys(STEP_FILE) as NotedStep[]) {
    const body = stepSpec(state, step);
    if (!body) continue;
    writeFileSync(resolve(dir, STEP_FILE[step]), body, "utf8");
  }
}

/**
 * Load a step's task note. The on-disk file wins (so your manual edits take effect);
 * falls back to the notes stored in the plan.
 */
export function loadStepTask(state: RunState, step: NotedStep): string | undefined {
  const file = resolve(runStepDir(state.id), STEP_FILE[step]);
  if (existsSync(file)) {
    const txt = readFileSync(file, "utf8").trim();
    if (txt) return txt;
  }
  return stepSpec(state, step);
}
